### ISSUE TITLE
Search button does not handle invalid language input

### ISSUE THREAD

**Issue by VanshChitransh** [MohamedDanis/opnhub#1] opened 2024-09-29 17:44 UTC
Description:
When using the search functionality on the platform, if an invalid or incorrect language name is entered (such as "Random"), the search button remains active, and no error or feedback is provided to inform the user about the invalid input. This may cause confusion for users who expect a result, even when the input is incorrect.

Steps to Reproduce:
Go to the search bar.
Enter a language name that is not valid or mistyped (e.g., "Random").
Click the search button.

Expected Behavior:
The system should disable the search button for invalid language input or display an error message prompting the user to correct the input.

Actual Behavior:
The search button remains active and clickable without providing any feedback to the user regarding the incorrect input.

Screenshots:
![Screenshot from 2024-09-29 22-53-49](https://github.com/user-attachments/assets/dc6393d8-968f-4b35-bcdc-1eb63e8f78e0)
![Screenshot from 2024-09-29 22-53-54](https://github.com/user-attachments/assets/e804bf0c-fef6-4dcb-83dc-b9163c0188d3)

Incorrect Input:
Random

Suggested Fix:
Implement input validation for correct language names.
Disable the search button or provide a feedback message until a valid language is entered.

Environment:
Browser: (e.g., Chrome 117)
Operating System: (e.g., Ubuntu 22.04)

**Comment by VanshChitransh** [comment] 2024-09-29 17:45
@MohamedDanis I would love to work on this issue, please assign it to me.

**Comment by Sauhard74** [comment] 2024-09-29 19:15
hey can i work on this issue? it seems easy yet a very important feature so I believe I can contribute and make the app better

**Comment by MohamedDanis** [comment] 2024-09-30 04:26
@VanshChitransh Please create a branch with your name and make a pr after completing

**Comment by MohamedDanis** [comment] 2024-09-30 04:27
@Sauhard74 already assigned to other, please check for another issues. Thank you

**Comment by imkeanserna** [comment] 2024-10-03 10:32
@MohamedDanis so sorry i pushed the code to solve this issue in my PR #21, i forgot to remove it! i think the issue is solved now.

**Comment by MohamedDanis** [comment] 2024-10-03 10:43
I don't get you ? @imkurosaki

**Comment by imkeanserna** [comment] 2024-10-03 10:55
I mean this issue is solved in my PR #21 
![image](https://github.com/user-attachments/assets/c263e23f-d306-42ef-9deb-61d0cc38c0b1)

**Comment by VanshChitransh** [comment] 2024-10-03 17:36
@MohamedDanis @imkurosaki is the issue still there?

**Comment by MohamedDanis** [comment] 2024-10-04 07:32
there is a new issue, you can work on that

**Closed as completed** 2024-10-04 07:31 UTC
Labels: bug, hacktoberfest
